#!/bin/bash

IMAGE_NAME=$1

#docker system prune

if [ -z "${IMAGE_NAME}" ];then
    echo "Repository name not set"
    exit 1
fi

if [ ! -z "(docker images | grep $IMAGE_NAME)" ];then
        echo "Remove previous version"
        docker rmi $IMAGE_NAME
fi

docker build --build-arg APP_NAME=checker  --build-arg CONF_NAME=config.toml -t $IMAGE_NAME .
docker image prune --filter label=stage=builder -f
